//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalDatabaseEntities : DbContext
    {
        public CarRentalDatabaseEntities()
            : base("name=CarRentalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<complaints> complaints { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<licenses> licenses { get; set; }
        public virtual DbSet<rents> rents { get; set; }
        public virtual DbSet<subscriptions> subscriptions { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
