//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalDatabaseEntities : DbContext
    {
        public CarRentalDatabaseEntities()
            : base("name=CarRentalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
    }
}
