//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public int RentID { get; set; }
        public string Description { get; set; }
        public System.DateTime Time { get; set; }
        public int Chk { get; set; }
    
        public virtual Rent Rent { get; set; }
    }
}
