//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subID { get; set; }
        public int accountID { get; set; }
        public Nullable<int> minute { get; set; }
        public Nullable<int> monthly { get; set; }
        public Nullable<int> company { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
